name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  builds:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout Repo Code

      - name: Login to Docker Hub
        uses: docker/login-action@v1

        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: BUILD the Docker Image
        run: docker build -t tegisty13/github_docker_image:${{ github.sha }}
        #run: docker build --file Dockerfile --tag tegisty13/github_docker_image:${{ github.sha }}
      
      - name: Docker Push
        run: docker push tegisty13/github_docker_image:${{ github.sha }}